1. Write a python function that computes the square of a number. The function should return the
output as a tuple in the following form: (a, a2) where a is the input value to the function.


In [4]:
def calcsqr(num):
    sqrtuple=num, num**2
    return sqrtuple

calcsqr(4)

(4, 16)

2. Write a function that can accept two strings as input and concatenate them and then print it as an
output.

In [1]:
def concatstr(a="",b=""):
    print(a+b)

concatstr("Bivek", "Kumar")    

BivekKumar


3. Write a function that can accept an integer number as an input and print "Even number" if the
number is even, otherwise print "Odd number".

In [3]:
def checknum(number):
    if number%2==0: print("Even number")
    else: print("Odd number")

checknum(6)    

Even number


4. Write a function that can print a dictionary where the keys are numbers between 1 and 20 (both
included) and the values are square of keys.

In [24]:
def gensqrdict(number=1):
    sqrdict={number : number**2 for number in range(1,21)}
    print(sqrdict)
gensqrdict() 

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400}


5. Write a function to compute the square-root of a given number. If the given number is negative,
your function should give an error message.

In [5]:
def computesqrt(number):
    if number>=0: print(number**0.5)
    else: print("error negative value")

computesqrt(64)    


8.0


6. Write a function to input two separate lists, one with names (name_list) and another with
numbers (number_list). Your function should then output another list (output_list) which contains
tuples of names and number.

name_list = [“Dan Mace”, “Connor Meyer”, “Adam Smith”, “John Watson”]
number_list = [98980000, 777890879, 123087699, 960008779]
output_list = [ (Dan Mace, 98980000), (Connor Meyer, 777890879), (Adam Smith, 123087699), (John
Watson, 960008779) ]

In [26]:
def mergelists(name_list1, number_list1):
    outputlist=[]
    for i in range(len(name_list1)):
        name=name_list1[i]
        number=number_list1[i]
        outputlist.append((name, number))
    return(outputlist)

name_list = ["Dan Mace", "Connor Meyer", "Adam Smith", "John Watson"]
number_list = [98980000, 777890879, 123087699, 960008779]

mergelists(name_list, number_list)



[('Dan Mace', 98980000),
 ('Connor Meyer', 777890879),
 ('Adam Smith', 123087699),
 ('John Watson', 960008779)]

7. With a given tuple (1,2,3,4,5,6,7,8,9,10), write a program to print the first half values in one line
and the last half values in another line.

In [27]:
numb=1,2,3,4,5,6,7,8,9,10
print(numb[:5])
print(numb[5:])

(1, 2, 3, 4, 5)
(6, 7, 8, 9, 10)


8. Write a function that takes in a list of usernames of students. The function should then output
another list which returns the email addresses by adding “@thebritishcollege.edu.np” to the
usernames in the list. The output of your function should be a list.
Input:
student_username = [ksmith, rsouza, lgarber, aghods, shassan, proy]
Output:
student_email = [ksmith@thebritishcollege.edu.np, rsouza@thebritishcollege.edu.np,
lgarber@thebritishcollege.edu.np, aghods@thebritishcollege.edu.np, shassan@thebritishcollege.edu.np,
proy@thebritishcollege.edu.np]

In [28]:
def domaingen(names_list):
    domain="@britishcollege.edu.np"
    student_email=[i+domain for i in names_list]
    print("student_email= ",student_email)


student_username = ["ksmith", "rsouza", "lgarber", "aghods", "shassan", "proy"]    
domaingen(student_username)

student_email=  ['ksmith@britishcollege.edu.np', 'rsouza@britishcollege.edu.np', 'lgarber@britishcollege.edu.np', 'aghods@britishcollege.edu.np', 'shassan@britishcollege.edu.np', 'proy@britishcollege.edu.np']


9. In the list given below, use a while loop to print the output. Your loop should run until all the
items in the list have been printed.
name_list = [ (Dan Mace, 98980000), (Connor Meyer, 777890879), (Adam Smith, 123087699), (John
Watson, 960008779) ]

Your output should look like:
Name: Dan Mace
Contact no: 98980000
.
.
.

In [29]:
name_list = [ ("Dan Mace", 98980000), ("Connor Meyer", 777890879), ("Adam Smith", 123087699), ("JohnWatson", 960008779) ]
i=0

while i < len(name_list):
    print("Name: ", name_list[i][0])
    print("Contact no: ", name_list[i][1])
    i += 1    



Name:  Dan Mace
Contact no:  98980000
Name:  Connor Meyer
Contact no:  777890879
Name:  Adam Smith
Contact no:  123087699
Name:  JohnWatson
Contact no:  960008779


10. Write a function that accepts a list of tuples as an input, and outputs the values as a dictionary
shown below:
input_list = [ (Dan Mace, 98980000), (Connor Meyer, 777890879), (Adam Smith, 123087699), (John
Watson, 960008779) ]
output_dict = {Dan Mace: 98980000, Connor Meyer: 777890879, Adam Smith: 123087699, John Watson:
960008779}

In [30]:
def geninfodict(info_list):
    output_dict={info_list[i][0]: info_list[i][1] for i in range(len(info_list))}
    print(output_dict)

input_list = [ ("Dan Mace", 98980000), ("Connor Meyer", 777890879), ("Adam Smith", 123087699), ("JohnWatson", 960008779)]  
geninfodict(input_list)  
   


{'Dan Mace': 98980000, 'Connor Meyer': 777890879, 'Adam Smith': 123087699, 'JohnWatson': 960008779}


11. Write a function to go through a string and count the number of words in the given string.
input_str = 'If you count the words in this sentence you will get twelve'
Your output must be as follows:
number of words: 12

In [31]:
def countwords(sentence):
    num=1
    for words in sentence:
        if words==" ":
            num+=1
    print("number of words: ", num)  

input_str = 'If you count the words in this sentence you will get twelve'         
countwords(input_str)


number of words:  12


12. Write a function to print Fibonacci sequence up-to the given term.
For example: If a user inputs 7, your function should print: 1, 1, 2, 3, 5, 8, 13
if a user inputs 9, your function should print: 1, 1, 2, 3, 5, 8, 13, 21, 34


In [6]:
def Fibonacci(number):
    n1, n2= 1,1
    if number>1:    
        print(n1,n2, end=" ")
        for i in range(2, number):
            next_term = n1 + n2
            print(next_term,end=" ")
            n1, n2 = n2, next_term
    elif number==1:
        print(1)
    else: print("number should be greater than 0")

Fibonacci(6)            

1 1 2 3 5 8 

13. Write a program to play a game of rock, paper and scissor between two players. Take two user
inputs from the keyboard and according to user's choice decide who wins.

In [9]:
choices = {"rock": 0, "paper": 1, "scissors": 2}

Player1 = choices[input("player1:rock,paper,scissors:").lower()]
Player2 = choices[input("player2:rock,paper,scissors").lower()]

score = (Player1 - Player2) % 3

if score == 1:
    print("Player1 wins")
elif score == 0:
    print("Tie")
else:
    print("Player2 wins")

player1:rock,paper,scissors:scissors
player2:rock,paper,scissorspaper
Player1 wins


14. Write a Python program to construct the following pattern.
1
22
333
4444
55555
666666
7777777
88888888
999999999

In [ ]:
for i in range(1, 10):
    for j in range(i):
        print(i, end="")
    print("")

1
22
333
4444
55555
666666
7777777
88888888
999999999


15. Write a Python function that accepts a hyphen-separated sequence of words as input and prints
the words in a hyphen-separated sequence after sorting them alphabetically.
For example:
If your input is : s-i-t-c-o-m
Your output should be : c-i-m-o-s-t

In [ ]:
def sorthifen(word):
    words=word.split("-")
    words.sort()
    return '-'.join(words)


sorthifen("s-i-t-c-o-m")    


'c-i-m-o-s-t'